# Generated by Django 4.2 on 2023-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="Pegawai", max_length=225, verbose_name="Username"
            ),
        ),
    ]
