# Generated by Django 4.2 on 2023-05-05 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="creator",
        ),
        migrations.AddField(
            model_name="activity",
            name="asign",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=225,
                null=True,
                verbose_name="asign",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="tanggal",
            field=models.DateField(
                default=datetime.date(2023, 5, 5), verbose_name="tanggal"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="waktu",
            field=models.TimeField(default="15:42:00", verbose_name="waktu"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="deskripsi",
            field=models.TextField(verbose_name="deskripsi"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="judul",
            field=models.CharField(max_length=225, verbose_name="judul"),
        ),
    ]
