# Generated by Django 4.2 on 2023-05-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="creator",
        ),
        migrations.AddField(
            model_name="activity",
            name="asign",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=225,
                null=True,
                verbose_name="asign",
            ),
        ),
    ]
