# Generated by Django 4.2 on 2023-05-08 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="asignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigned users",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="waktu",
            field=models.TimeField(default="13:47:43", verbose_name="waktu"),
        ),
    ]
