# Generated by Django 4.2 on 2023-05-02 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_remove_activity_creator_activity_asign"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="tanggal",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="tanggal"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="deskripsi",
            field=models.TextField(verbose_name="deskripsi"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="judul",
            field=models.CharField(max_length=225, verbose_name="judul"),
        ),
    ]
