# Generated by Django 4.2 on 2023-05-05 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_activity_tanggal_alter_activity_deskripsi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="waktu",
            field=models.TimeField(default="14:27:48", verbose_name="waktu"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="tanggal",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="tanggal"
            ),
        ),
    ]
