# Generated by Django 4.2 on 2023-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_activity_waktu_alter_activity_tanggal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="asign",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=225,
                null=True,
                verbose_name="asign",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="waktu",
            field=models.TimeField(default="14:30:29", verbose_name="waktu"),
        ),
    ]
