# Generated by Django 4.2 on 2023-05-05 07:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0005_alter_activity_asign_alter_activity_waktu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="asign",
        ),
        migrations.AddField(
            model_name="activity",
            name="asignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigned users",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="tanggal",
            field=models.DateField(
                default=datetime.date(2023, 5, 5), verbose_name="tanggal"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="waktu",
            field=models.TimeField(default="14:36:17", verbose_name="waktu"),
        ),
    ]
