# Generated by Django 4.2 on 2023-05-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_remove_activity_asign_activity_asignees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="waktu",
            field=models.TimeField(default="14:39:29", verbose_name="waktu"),
        ),
    ]
