# Generated by Django 4.2 on 2023-05-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0012_alter_activity_waktu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="waktu",
            field=models.TimeField(default="15:25:25", verbose_name="waktu"),
        ),
    ]
